apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: prod
  labels:
    app: notification-service
spec:
  selector:
    matchLabels:
      app: notification-service
  replicas: 1
  template:
    metadata:
      name: notification-pod
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ${REPOSITORY_URI}/jeontongju-notification-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
