apiVersion: v1
kind: Service
metadata:
  name: redis-auction-service
  namespace: prod
  labels:
    app: redis-auction
spec:
  ports:
    - port: 6379
  clusterIP: None
  selector:
    app: redis-auction
