apiVersion: apps/v1
kind: Deployment
metadata:
  name: seller-deployment
  namespace: prod
  labels:
    app: seller-service
spec:
  selector:
    matchLabels:
      app: seller-service
  replicas: 1
  template:
    metadata:
      name: seller-pod
      labels:
        app: seller-service
    spec:
      containers:
        - name: seller-service
          image: ${REPOSITORY_URI}/jeontongju-seller-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
