apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  namespace: prod
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      name: config-pod
      labels:
        app: config-service
    spec:
      containers:
        - image: ${REPOSITORY_URI}/jeontongju-config-service
          imagePullPolicy: Always
          name: config-service
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
