apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-deployment
  namespace: prod
  labels:
    app: auction-service
spec:
  selector:
    matchLabels:
      app: auction-service
  replicas: 1
  template:
    metadata:
      name: auction-pod
      labels:
        app: auction-service
    spec:
      containers:
        - name: auction-service
          image: jtg/auction-service:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
