apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-deployment
  namespace: prod
  labels:
    app: auction-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: auction-service
  replicas: 2
  template:
    metadata:
      name: auction-pod
      labels:
        app: auction-service
    spec:
      containers:
        - name: auction-service
          image: ${REPOSITORY_URI}/jeontongju-auction-service
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 2
