apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: prod
  labels:
    app: api-gateway-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: api-gateway-service
  replicas: 2
  template:
    metadata:
      name: api-gateway-pod
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: ${REPOSITORY_URI}/jeontongju-api-gateway-service:${IMAGE_TAG}
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 2
