apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: prod
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: api-gateway-service
