apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: prod
  labels:
    app: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1
  template:
    metadata:
      name: product-pod
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ${REPOSITORY_URI}/jeontongju-product-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
