apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: prod
  labels:
    app: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1
  template:
    metadata:
      name: order-pod
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ${REPOSITORY_URI}/jeontongju-order-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
