apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  namespace: prod
  labels:
    app: discovery-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
  selector:
    matchLabels:
      app: discovery-service
  replicas: 1
  template:
    metadata:
      name: discovery-pod
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: ${REPOSITORY_URI}/jeontongju-discovery-service
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8761
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 2
