apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  namespace: prod
  labels:
    app: discovery-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
  selector:
    matchLabels:
      app: discovery-service
  replicas: 1
  template:
    metadata:
      name: discovery-pod
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: ${REPOSITORY_URI}/jeontongju-discovery-service
          ports:
            - containerPort: 8761
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 2
