apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  namespace: prod
  labels:
    app: discovery-service
spec:
  selector:
    matchLabels:
      app: discovery-service
  replicas: 1
  template:
    metadata:
      name: discovery-pod
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: jtg/discovery:latest
          ports:
            - containerPort: 8761
          imagePullPolicy: Always
