apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
  namespace: prod
  labels:
    app: storage-service
spec:
  selector:
    matchLabels:
      app: storage-service
  replicas: 1
  template:
    metadata:
      name: storage-pod
      labels:
        app: storage-service
    spec:
      containers:
        - name: storage-service
          image: ${REPOSITORY_URI}/jeontongju-storage-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
