apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: prod
  labels:
    app: consumer-service
spec:
  selector:
    matchLabels:
      app: consumer-service
  replicas: 1
  template:
    metadata:
      name: consumer-pod
      labels:
        app: consumer-service
    spec:
      containers:
        - name: consumer-service
          image: ${REPOSITORY_URI}/jeontongju-consumer-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
