apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-deployment
  namespace: prod
  labels:
    app: coupon-service
spec:
  selector:
    matchLabels:
      app: coupon-service
  replicas: 1
  template:
    metadata:
      name: coupon-pod
      labels:
        app: coupon-service
    spec:
      containers:
        - name: coupon-service
          image: ${REPOSITORY_URI}/jeontongju-coupon-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
