apiVersion: v1
kind: Pod
metadata:
  name: subscription-batch-service
  namespace: prod
  labels:
    app: subscription-batch-service
spec:
  restartPolicy: Never
  containers:
    - name: subscription-batch-service
      image: ${REPOSITORY_URI}/jeontongju-subscription-batch-service${IMAGE_TAG}
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
