apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: prod
  labels:
    app: payment-service
spec:
  selector:
    matchLabels:
      app: payment-service
  replicas: 1
  template:
    metadata:
      name: payment-pod
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ${REPOSITORY_URI}/jeontongju-payment-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
