apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  labels:
    app: kafdrop
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: kafdrop
  ports:
    - port: 9000
      targetPort: 9000
