apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  namespace: prod
  labels:
    app: review-service
spec:
  selector:
    matchLabels:
      app: review-service
  replicas: 1
  template:
    metadata:
      name: review-pod
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: ${REPOSITORY_URI}/jeontongju-review-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
