apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  namespace: prod
  labels:
    app: authentication-service
spec:
  selector:
    matchLabels:
      app: authentication-service
  replicas: 1
  template:
    metadata:
      name: authentication-pod
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: ${REPOSITORY_URI}/jeontongju-authentication-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
