apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  namespace: prod
  labels:
    app: authentication-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: authentication-service
  replicas: 1
  template:
    metadata:
      name: authentication-pod
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: ${REPOSITORY_URI}/jeontongju-authentication-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 2
