apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  namespace: prod
  labels:
    app: search-service
spec:
  selector:
    matchLabels:
      app: search-service
  replicas: 1
  template:
    metadata:
      name: search-pod
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: ${REPOSITORY_URI}/jeontongju-search-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
