apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  namespace: prod
  labels:
    app: search-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: search-service
  replicas: 2
  template:
    metadata:
      name: search-pod
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: ${REPOSITORY_URI}/jeontongju-search-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 2
