apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-ss-configuration
  namespace: prod
  labels:
    app: redis
data:
  master.conf: |
    requirepass bitroot
    maxmemory 400mb
    maxmemory-policy allkeys-lru
    maxclients 20000
    timeout 300
    appendonly yes
    dbfilename dump.rdb
    dir /data
  slave.conf: |
    requirepass bitroot
    slaveof redis-ss-0.redis-ss.redis 6379
    maxmemory 400mb
    maxmemory-policy allkeys-lru
    maxclients 20000
    timeout 300
    dir /data
